sudo: required

services:
  - docker

language: go

go:
  - 1.11

env:
  - GO111MODULE=on

git:
  depth: false
  submodules: false

before_script:
  - go get
  - make test
  - make

script:
  - make
  - make docker

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  provider: script
  skip_cleanup: true # Important, otherwise the build output would be purged.
  # use rocket to deploy itself :)
  script: dist/rocket && make docker_push
  on:
    repo: astrocorp42/rocket
    tags: true # The deployment happens only if the commit has a tag

notifications:
  email:
    on_success: never # default: change
